version: '2'
services:
  nginx:   
    build: .
    ports:
     - "80:80"
    volumes:
     - assets_volume:/app/public 
  app:
    image: juanlb/rails-multibase:sqlite3
    environment:
      - RAILS_ENV=production
    volumes:
     - assets_volume:/app/public 
volumes:
  assets_volume: